# Azure Pipeline that test detect-secrets in code
trigger:
  branches:
    include:
    - "main"
  paths:
    exclude:
    - .git/*
    - .mypy_cache/*
    - .pytest_cache/*
    - __pycache__/*
    - build/*
    - dist/*
    - src/*
    - docs/*
    - config/*
    - .devcontainer/*

variables:
  - name: varPythonVersion
    value:  '3.7'
  - name: secretsInTests
    value:  '8'

pool:
  vmImage: 'ubuntu-20.04'

stages:
- stage: TestDetectSecretsStage
  displayName: Test Detect secrets Stage
  jobs:
  - job: TestDetectSecretsJob
    displayName: Test Detect secrets Job
    steps:     
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(varPythonVersion)'
      displayName: 'Use Python $(varPythonVersion)'    
    - task: Bash@3
      displayName: 'Detect-secrets'
      env:          
        inputPath: $(varInputPath)
        excludeFiles: $(varExcludeFiles)
        options: $(varOptions)
        optionsv1: $(varOptionsv1)
        excludedSecretsFile: $(varExcludedSecretsFile)       
      inputs:
        targetType: 'inline'
        script: |
            # run test-detect-secrets.sh
            pipelines/utils/test-detect-secrets.sh $(secretsInTests)

