FROM continuumio/miniconda3:latest

ARG USERNAME=dsuser
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

RUN apt-get update \
    && apt-get install -y gnupg software-properties-common

# apt stuff
RUN apt-get update \
    && export DEBIAN_FRONTEND=noninteractive \
    # install missing packages
    && mkdir -p /usr/share/man/man1 \
    && apt-get install -y sudo git curl make procps lsb-release vim jq libicu[0-9][0-9] python3-distutils \
    # add sudo support
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    # install azure-cli
    && curl -sL https://aka.ms/InstallAzureCLIDeb | bash 

# change conda to be owned by the user
RUN chown -R $USERNAME:$USERNAME /opt/conda

# now everything from here uses the normal user
USER $USERNAME

# configure az cli to automatically install extension
RUN az config set extension.use_dynamic_install=yes_without_prompt

# copy requirements
COPY ./requirements_*.txt  /home/$USERNAME/

# init conda 
RUN conda init bash 

# install tox, pre-commit and detect-secrets
RUN pip install tox==3.21.3 pre-commit==2.10.0 detect-secrets==1.0.3 

# install shared libraries
RUN pip install -r /home/$USERNAME/requirements_shared.txt

# install test libraries
RUN pip install -r /home/$USERNAME/requirements_blobtext.txt

# back to default shell
SHELL ["/bin/sh", "-c"]

CMD [ "sleep", "infinity" ]